### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by probonopd** [antony-jr/Test-AppImageUpdater#2]
When invoked without any parameters, it just does nothing:

```
me@host:~$ /home/me/Downloads/Test-git.28cfe54-x86_64.AppImage
```

When invoked with the path to itself as a parameter, it gives an ERROR CODE:

```
me@host:~$ /home/me/Downloads/Test-git.28cfe54-x86_64.AppImage /home/me/Downloads/Test-git.28cfe54-x86_64.AppImage 
ERROR CODE::  0
```

How can I make `Test-git.28cfe54-x86_64.AppImage` to check itself for updates?

**Comment by antony-jr** [comment]
that should be programmed.
**Like This**
```
AIUpdaterBridge Bridge;
Bridge.setAppImageUpdateInformation(QString(argv[0]));
```

**Comment by probonopd** [comment]
I thought it is possible to supply the AppImage which should be updated as an argument?

**Comment by antony-jr** [comment]
That is possible too. There must be something buggy! Let me see it!

**Comment by antony-jr** [comment]
@probonopd I found the error by debugging it.
```
QAIUpdateInformation:: Update information found.

QAIUpdateInformation::  ""
QAIUpdateInformation:: empty update string returned :: "Test-git.28cfe54-x86_64.AppImage"
ERROR CODE::  0
```
I think I did not fill in any information ?

**Comment by antony-jr** [comment]
How am I supposed to fill in the **information** ?

**Comment by antony-jr** [comment]
@probonopd even a lot of apps which are deployed with **travis-ci** does not have a **AppImage Information** 

Only **AppImageTools** tend to have **Update Information embeded!**

# Example

```
QAIUpdateInformation:: Update information found.

QAIUpdateInformation::  ""
QAIUpdateInformation:: empty update string returned :: "fastqt-0.2.3-linux-x86_64.appimage"
ERROR CODE::  0
```

**Comment by probonopd** [comment]
> @probonopd even a lot of apps which are deployed with travis-ci does not have a AppImage 

Yes, we know. You can find a list of AppImages that have update information on https://appimage.github.io/apps/ - look for the green "checkmark" symbol.

**Comment by probonopd** [comment]
> QAIUpdateInformation:: Update information found.

In this case it should say "__no__ update information found", and it should offer to update itself (the updater) because in the meantime there may have been a new form of update information which may require a newer updater. AppImageUpdate has this implemented.

**Comment by antony-jr** [comment]
@probonopd the issue is solved , I just added my **GITHUB_TOKEN** and it deployed the appimage with **UpdateInformation** , please check https://travis-ci.org/antony-jr/Test-AppImageUpdater/builds/325553279#L867

**Comment by antony-jr** [comment]
you should have some good documentation about this stuff!

**Comment by antony-jr** [comment]
Since I do not have a **zsync** file  , it may not work on normal mode.
```
QAIUpdateInformation:: Update information found.

QAIUpdateInformation::  "gh-releases-zsync|Test-AppImageUpdater|(null)|continuous|Test-AppImageUpdater*-x86_64.AppImage.zsync"
AIUpdaterBridge:: github release link :: QUrl("https://api.github.com/repos/Test-AppImageUpdater/(null)/releases/tags/continuous")
AIUpdaterBridge:: network error ::  QNetworkReply::NetworkError(ContentNotFoundError)
ERROR CODE::  7
```

**Comment by antony-jr** [comment]
> it should offer to update itself (the updater) because in the meantime there may have been a new form of update information which may require a newer updater.

If we add the **Update Information** on the very first **release** then it will update **itself** automatically when a new **release** is made. Then why worry. The updater returned **empty** Update String because **the magic codes were correct** but the **author** did not embed the **UpdateInformation** which is not the **Updaters** fault , right?

Without any **Update Information** on the first **release** , it is impossible to update but If you have **added** some temporary **update** point **then** on the next release you can change the **temporary point** too.. Thats why **AppImageUpdaterBridge** has in-block configuration , so that we can change the update **transport** anytime we want

So What exactly is the **issue** here ? I can't fathom it quite well...

**Comment by probonopd** [comment]
I think it would be good if the error message would be a bit more clear.

**Comment by antony-jr** [comment]
@probonopd don't worry about that because there are so many error codes that I don't want to use switch because this is just a test.
